version: '3'
services:
  bot:
    image: vanopiano/download_bot:latest
    build:
      context: .
    restart: on-failure
    env_file: [.env]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # for debug
      # - ./:/app

  ytdl:
    image: vanopiano/download_ytdl:latest
    build:
      dockerfile: Dockerfile.ytdl
    restart: on-failure
