version: '3'
services:
  bot:
    image: vanopiano/download_bot:latest
    build:
      context: .
    restart: on-failure
    env_file: [.env]
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data:/app/data
